name: CI
on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - "**.md"

env:
  TZ: Asia/Tokyo

jobs:
  test:
    name: run test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust_version: ["stable", "1.61.0"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust_version }}
          components: rustfmt, clippy
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
