name: CI
on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"
    branches:
      - master

env:
  TZ: Asia/Tokyo

jobs:
  test:
    name: run test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust_version: ["stable", "1.69.0"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust_version }}
          components: rustfmt, clippy
      - run: cargo fmt --all -- --check
      - uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-review'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: cargo test --all-features
